### ISSUE TITLE
[ Desgin ]  Check desgin all page 

### ISSUE THREAD

**Issue by fdhhhdjd** [linhnguyen-gt/mini-zalo-demo#4]

**Comment by haofrontend-dev** [comment]
1. Trang chủ:
 - Thêm Popup quan tấm OA
 - Thêm thẻ thành viên Moshav Farm
 - Thêm UI Bài viết mới nhất
3. Giỏ hàng
- App dụng voucher
4. Add Page Order Success
5. Tài Khoản
- Thêm page Đơn hàng của bạn
- Thêm Page Lịch sử mua hàng
- Thêm Page Thông tin tài khoản
- Thêm Affiliate Marketing - Mã giới thiệu: Mã QR và Link chia sẽ

**Comment by linhnguyen-gt** [comment]
<img width="1473" alt="Screenshot 2023-10-31 at 09 39 23" src="https://github.com/linhnguyen-gt/mini-zalo-demo/assets/43808684/266d3110-be0a-4814-8a57-99e8329841bd">

please check https://docs.google.com/spreadsheets/d/1ui_r8J-U-QMNdDLqFJjBaqK1hq6K_cW7ZZeunJv54To/edit#gid=659737933

**Comment by linhnguyen-gt** [comment]
> 1. Trang chủ:
> 
> * Thêm Popup quan tấm OA - Pending
> * Thêm thẻ thành viên Moshav Farm - Pending
> * Thêm UI Bài viết mới nhất - Pending
> 
> 3. Giỏ hàng
> 
> * App dụng voucher - Pending
> * Check Phần Picker time trong page Cart bị lõi. 
> * Add Toast Message khi thêm giỏ hàng.
> 
> 4. Add Page Order Success
> 5. Tài Khoản
> 
> * Thêm page Đơn hàng của bạn
> * Thêm Page Lịch sử mua hàng
> * Thêm Page Thông tin tài khoản
> * Thêm Affiliate Marketing - Mã giới thiệu: Mã QR và Link chia sẽ - Pending

**Comment by fdhhhdjd** [comment]
Ok check Done
