### ISSUE TITLE
[Test] Test release version 06 new day 06/11/2023

### ISSUE THREAD

**Issue by fdhhhdjd** [linhnguyen-gt/mini-zalo-demo#61]
- Test all pages if error or problem comment error and image

# Version 6:  Chưa fix total product

![image](https://github.com/linhnguyen-gt/mini-zalo-demo/assets/63393170/c9dabe4c-9389-4e09-b56e-01090f474f20)

# Version 7: Đã fix total  product

![image](https://github.com/linhnguyen-gt/mini-zalo-demo/assets/63393170/82cf9652-a0ed-42a5-94e2-02e1eea8f437)

**Comment by NguyenVoTien** [comment]
Chưa có tổng tiền phần giỏ hàng

**Comment by fdhhhdjd** [comment]
> Chưa có tổng tiền phần giỏ hàng
Chụp hình lại nhé

**Comment by fdhhhdjd** [comment]
Có hình ảnh nữa nhé mọi người

**Comment by fdhhhdjd** [comment]
Bug page /search 

![image](https://github.com/linhnguyen-gt/mini-zalo-demo/assets/63393170/e8320204-95d8-449d-9250-ba719eb8ed8e)
